#!/usr/bin/env python3
"""NCypher rigor hook (PreToolUse on Write/Edit/MultiEdit).

Blocks hand-edits into the gitignored ``data/`` tree. Raw data, scored tables and
figures are fetched or generated by the scripts, never hand-written, so this keeps the
analysis reproducible and stops data leaking into a commit. This is the kind of
ML-genomics discipline Pollard/Whalen look for, enforced by construction rather than
by good intentions.

Fail-open by design: any unexpected input allows the write, so the hook can never trap
the session. Exit code 2 blocks the tool call and feeds the reason back to Claude.
"""
import json
import sys

try:
    payload = json.load(sys.stdin)
    path = ((payload.get("tool_input") or {}).get("file_path") or "").replace("\\", "/")
    is_data = path.startswith("data/") or "/NCypher/data/" in path
    if is_data:
        sys.stderr.write(
            "NCypher rigor hook: data/ is gitignored and generated by the scripts, not "
            "hand-edited. Regenerate via scripts/ (or write the output there) instead of "
            "editing files under data/.\n"
        )
        sys.exit(2)  # block, and surface the reason to Claude
except Exception:
    pass  # fail open: never trap the session on a parse issue

sys.exit(0)  # allow
